require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Capfile'
  NewCops: enable

Style/GlobalVars:
  AllowedVariables:
    - $preservation_manager_proxy

Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/HashSyntax:
   EnforcedShorthandSyntax: either

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 3

RSpecRails/InferredSpecType:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
